name: backend_api
version: 1.0.0
description: OpenAPI API client
homepage: homepage

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  dio: ^4.0.6
  built_value: ^8.1.4
  built_collection: ^5.0.0

dev_dependencies:
  built_value_generator: ^8.0.0
  build_runner: any
  test: ^1.21.1
